---
title: "Dating Profiles"
author: "Susan VanderPlas"
date: "October 6, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, error = F)

library(stringr)
library(dplyr)
library(tidyr)
library(ggplot2)

data <- read.csv("Data/DatingProfiles.csv")
data$Height.Orig <- data$Height
data$Height <- data$Height %>%
  str_extract("\\d{0,1}\\.\\d{0,2}m") %>%
  str_replace_all("m", "") %>%
  as.numeric()

data$Height <- data$Height * 3.28084 # Meters -> Feet

data <- filter(data, !is.na(Height))
```

# Height by Gender

34456 unique profiles were collected from a dating site. Of those profiles, `r nrow(data)` contained self-reported height. As women are on average shorter than men, the distributions for each gender are shown separately. 

```{r height-by-gender, fig.width = 8, fig.height = 4}
ggplot(data = data, aes(x = Height, fill = gender)) + 
scale_x_continuous("Height (ft)", limits = c(4, 7)) + 
scale_y_continuous("# Profiles") + 
geom_histogram(binwidth = .1, color = "black") + 
facet_wrap(~gender, scales = "free")
```


```{r height-by-gender2, fig.width = 8, fig.height = 4}
ggplot(data = data, aes(x = Height, fill = gender)) + 
scale_x_continuous("Height (ft)", limits = c(4, 7)) + 
scale_y_continuous("# Profiles") + 
geom_histogram(binwidth = 1/6, color = "black") + 
facet_wrap(~gender, scales = "free")
```

```{r height-by-gender3, fig.width = 8, fig.height = 4}
ggplot(data = data, aes(x = Height, fill = gender)) + 
scale_x_continuous("Height (ft)", limits = c(4, 7)) + 
scale_y_continuous("# Profiles") + 
geom_density(adjust = 1.25, color = "black") + 
facet_wrap(~gender, scales = "free")
```
