---
title: "Random (and not-so-random) Data"
author: "Susan VanderPlas"
date: "09/08/2014"
output:
  knitrBootstrap::bootstrap_document:
    title: "Cool Packages"
    theme: cerulean
    highlight: sunburst
    theme.chooser: FALSE
    highlight.chooser: FALSE
---
<div class="jumbotron">
<h2> Interesting R Packages </h2>
<small>This page contains a list of R packages that are interesting or have the potential to be useful to me at a later date.
[Main page](index.html).</small>
</div>


## R packages

- [vembedr](https://cran.rstudio.com/web/packages/vembedr/vignettes/embed.html): Embed videos from YouTube and Vimeo in Rmarkdown documents. Use ALL the puppy videos!

- [rvest](https://github.com/hadley/rvest): A BeautifulSoup-like package for R. 

- [USAboundaries](https://github.com/ropensci/USAboundaries): A package with US state/territory boundaries, counties, congressional districts, and zip codes from 1629 to 2000.

## Shiny packages: 
- [shinyTable](https://github.com/trestletech/shinyTable): implements [Handsontable](http://handsontable.com/) for shiny, providing a spreadsheet-like editor in a web browser (data can then be read into R)

- [shinyRGL](https://github.com/trestletech/shinyRGL): provides webGL bindings, so that 3D graphics can be manipulated within shiny apps. Somewhat more difficult to set up the shiny-server backend, but still a very neat effect. 

- shinyBS package: Make bootstrap work nicely with Shiny and allows modal windows that are overlays. Good for documentation - help files show up elsewhere. 

- [leaflet-shiny](https://github.com/jcheng5/leaflet-shiny): adds shiny bindings for [Leaflet.js](http://leafletjs.com/), which makes mobile-friendly interactive maps

- [shiny-gridster](https://github.com/wch/shiny-gridster): use the [gridster](http://gridster.net/) library with shiny. Drag-and-drop multi-column grid layouts for web pages. 

- [shiny-jsdemo](https://github.com/wch/shiny-jsdemo): R shiny bindings for [gridster](http://gridster.net/), [justgage](http://justgage.com/), and [highcharts](http://www.highcharts.com/). Calls the shiny-gridster package as a dependency. Also includes a status panel. 

- [shiny-sky](https://github.com/AnalytixWare/ShinySky): Includes styled buttons and alerts not present in default shiny apps. Also adds event buttons and busy indicators, and includes [handsontable](http://handsontable.com/) and [jsTree](http://www.jstree.com/) bindings. Adds color input as well. 
